//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Application Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oops! Application was crashed.
        ///Will Re-launching it?
        ///
        ///--- Debug Infomation ---
        ///{0}
        ///{1}
        ///--- StackTrace ---
        ///{2}
        ///--- End of StackTrace --- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationErrorTrace {
            get {
                return ResourceManager.GetString("ApplicationErrorTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonErrorOccurred {
            get {
                return ResourceManager.GetString("CommonErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... other {0} errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_WithCount {
            get {
                return ResourceManager.GetString("Error_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatYearMonth {
            get {
                return ResourceManager.GetString("FormatYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Latter {
            get {
                return ResourceManager.GetString("Latter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jan. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_01 {
            get {
                return ResourceManager.GetString("MonthShort_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feb. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_02 {
            get {
                return ResourceManager.GetString("MonthShort_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_03 {
            get {
                return ResourceManager.GetString("MonthShort_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apr. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_04 {
            get {
                return ResourceManager.GetString("MonthShort_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   May. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_05 {
            get {
                return ResourceManager.GetString("MonthShort_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jun. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_06 {
            get {
                return ResourceManager.GetString("MonthShort_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jul. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_07 {
            get {
                return ResourceManager.GetString("MonthShort_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aug. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_08 {
            get {
                return ResourceManager.GetString("MonthShort_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sep. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_09 {
            get {
                return ResourceManager.GetString("MonthShort_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oct. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_10 {
            get {
                return ResourceManager.GetString("MonthShort_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nov. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_11 {
            get {
                return ResourceManager.GetString("MonthShort_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dec. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthShort_12 {
            get {
                return ResourceManager.GetString("MonthShort_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No accounts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon/Thu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Mon_Thu {
            get {
                return ResourceManager.GetString("Week_Mon_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue/Fri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Tue_Fri {
            get {
                return ResourceManager.GetString("Week_Tue_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed/Sat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Wed_Sat {
            get {
                return ResourceManager.GetString("Week_Wed_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
