//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Genshin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Genshin() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.Genshin", typeof(Genshin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   No signature set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account_NoStatusMessage {
            get {
                return ResourceManager.GetString("Account_NoStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agnidus Agate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_AgnidusAgate {
            get {
                return ResourceManager.GetString("Ascension_AgnidusAgate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brilliant Diamond に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_BrilliantDiamond {
            get {
                return ResourceManager.GetString("Ascension_BrilliantDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nagadus Emerald に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_NagadusEmerald {
            get {
                return ResourceManager.GetString("Ascension_NagadusEmerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prithiva Topaz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_PrithivaTopaz {
            get {
                return ResourceManager.GetString("Ascension_PrithivaTopaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shivada Jade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_ShivadaJade {
            get {
                return ResourceManager.GetString("Ascension_ShivadaJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vajrada Amethyst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_VajradaAmethyst {
            get {
                return ResourceManager.GetString("Ascension_VajradaAmethyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Varunada Lazurite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_VarunadaLazurite {
            get {
                return ResourceManager.GetString("Ascension_VarunadaLazurite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vayuda Turquoise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ascension_VayudaTurquoise {
            get {
                return ResourceManager.GetString("Ascension_VayudaTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reputation Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string City_ReputationLevel {
            get {
                return ResourceManager.GetString("City_ReputationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crystal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Crystal {
            get {
                return ResourceManager.GetString("Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anemo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Anemo {
            get {
                return ResourceManager.GetString("Element_Anemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cryo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Cryo {
            get {
                return ResourceManager.GetString("Element_Cryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dendro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Dendro {
            get {
                return ResourceManager.GetString("Element_Dendro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Electro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Electro {
            get {
                return ResourceManager.GetString("Element_Electro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Geo {
            get {
                return ResourceManager.GetString("Element_Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hydro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Hydro {
            get {
                return ResourceManager.GetString("Element_Hydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pyro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Element_Pyro {
            get {
                return ResourceManager.GetString("Element_Pyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mora に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mora {
            get {
                return ResourceManager.GetString("Mora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anemoculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Anemo {
            get {
                return ResourceManager.GetString("Oculus_Anemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cryoculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Cryo {
            get {
                return ResourceManager.GetString("Oculus_Cryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dendroculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Dendro {
            get {
                return ResourceManager.GetString("Oculus_Dendro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Electroculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Electro {
            get {
                return ResourceManager.GetString("Oculus_Electro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geoculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Geo {
            get {
                return ResourceManager.GetString("Oculus_Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hydroculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Hydro {
            get {
                return ResourceManager.GetString("Oculus_Hydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pyroculi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Oculus_Pyro {
            get {
                return ResourceManager.GetString("Oculus_Pyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primogems に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Primogems {
            get {
                return ResourceManager.GetString("Primogems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freedom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_1_1 {
            get {
                return ResourceManager.GetString("TalentBook_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resistance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_1_2 {
            get {
                return ResourceManager.GetString("TalentBook_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ballad に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_1_3 {
            get {
                return ResourceManager.GetString("TalentBook_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prosperity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_2_1 {
            get {
                return ResourceManager.GetString("TalentBook_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diligence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_2_2 {
            get {
                return ResourceManager.GetString("TalentBook_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_2_3 {
            get {
                return ResourceManager.GetString("TalentBook_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transience に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_3_1 {
            get {
                return ResourceManager.GetString("TalentBook_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elegance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_3_2 {
            get {
                return ResourceManager.GetString("TalentBook_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_3_3 {
            get {
                return ResourceManager.GetString("TalentBook_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admonition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_4_1 {
            get {
                return ResourceManager.GetString("TalentBook_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ingenuity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_4_2 {
            get {
                return ResourceManager.GetString("TalentBook_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Praxis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_4_3 {
            get {
                return ResourceManager.GetString("TalentBook_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_5_1 {
            get {
                return ResourceManager.GetString("TalentBook_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Justice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_5_2 {
            get {
                return ResourceManager.GetString("TalentBook_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_5_3 {
            get {
                return ResourceManager.GetString("TalentBook_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_6_1 {
            get {
                return ResourceManager.GetString("TalentBook_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_6_2 {
            get {
                return ResourceManager.GetString("TalentBook_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_6_3 {
            get {
                return ResourceManager.GetString("TalentBook_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_7_1 {
            get {
                return ResourceManager.GetString("TalentBook_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_7_2 {
            get {
                return ResourceManager.GetString("TalentBook_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentBook_7_3 {
            get {
                return ResourceManager.GetString("TalentBook_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elemental Burst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentType_ElementalBurst {
            get {
                return ResourceManager.GetString("TalentType_ElementalBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elemental Skill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentType_ElementalSkill {
            get {
                return ResourceManager.GetString("TalentType_ElementalSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Attack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TalentType_NormalAttack {
            get {
                return ResourceManager.GetString("TalentType_NormalAttack", resourceCulture);
            }
        }
    }
}
