//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to save the screenshot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Error_FailedSaveScreenshot {
            get {
                return ResourceManager.GetString("App_Error_FailedSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New screenshot was saved! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Notify_Screenshot_Saved {
            get {
                return ResourceManager.GetString("App_Notify_Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App launched.
        ///Can be opened from the task tray. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Notify_WakeUp {
            get {
                return ResourceManager.GetString("App_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inconsistent UID format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_400 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target player not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_404 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This API is currently unavailable due to destructive changes made by an in-game update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_424 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many requests. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_429 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal server error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_500 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This API is currently unavailable due to the service being temporarily suspended. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_503 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception error occurred during reading config file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Config_FailToLoad {
            get {
                return ResourceManager.GetString("Error_Config_FailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The corresponding HoYoLab account (UID: {0}) is not authenticated and therefore cannot be accessed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_HoYoLabAccount_NotAuthenticated {
            get {
                return ResourceManager.GetString("Error_HoYoLabAccount_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In your HoYoLab account, you do not possess the &apos;UID {0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_HoYoLabAccount_UIDNotFound {
            get {
                return ResourceManager.GetString("Error_HoYoLabAccount_UIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open registry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Registry_FailedToOpen {
            get {
                return ResourceManager.GetString("Error_Registry_FailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use 2+ consecutive path delimiter characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_DoubleSeparator {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_DoubleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use a space as the first character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_FirstCharacterIsSpace {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_FirstCharacterIsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_InvalidCharacters {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use a directory delimiter character at the end of the format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_LastCharacterIsSeparate {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_LastCharacterIsSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play time : {0} hour(s) {1} minute(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameApp_Notify_PlayTime_Result {
            get {
                return ResourceManager.GetString("GameApp_Notify_PlayTime_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Impact launch detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameApp_Notify_WakeUp {
            get {
                return ResourceManager.GetString("GameApp_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (UID:{1}) will remove from the account list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_Message {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove this account? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_Title {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_WindowTitle {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Character_Level {
            get {
                return ResourceManager.GetString("UI_Character_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Weapons_Level {
            get {
                return ResourceManager.GetString("UI_Weapons_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refinement Rank {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Weapons_RefinementRank {
            get {
                return ResourceManager.GetString("UI_Weapons_RefinementRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Days: {0} Achieve: {1}
        ///Spiral Abyss: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_AccountInfo_Infomation {
            get {
                return ResourceManager.GetString("UIName_AccountInfo_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load game data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_AccountInfo_Infomation_Failed {
            get {
                return ResourceManager.GetString("UIName_AccountInfo_Infomation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_CharacterFrame_FailedToLoad {
            get {
                return ResourceManager.GetString("UIName_CharacterFrame_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_CharacterFrame_Nothing {
            get {
                return ResourceManager.GetString("UIName_CharacterFrame_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle_Common {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle2_1 {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latter Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle2_2 {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Floor {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Update : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_LatestUpdate {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_LatestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Level {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Locked {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Timestamp {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Warning] The application is currently in safe mode and is read-only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_SafeMode {
            get {
                return ResourceManager.GetString("Warning_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enhancement Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_EnhancementCalculator {
            get {
                return ResourceManager.GetString("WindowName_EnhancementCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Announcement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameAnnouncement {
            get {
                return ResourceManager.GetString("WindowName_GameAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle Chronicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameRecord {
            get {
                return ResourceManager.GetString("WindowName_GameRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real-Time Notes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spiral Abyss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Diary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiary {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Pathbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetail {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetail", resourceCulture);
            }
        }
    }
}
