//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to save the screenshot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string App_Error_FailedSaveScreenshot {
            get {
                return ResourceManager.GetString("App_Error_FailedSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New screenshot was saved! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string App_Notify_Screenshot_Saved {
            get {
                return ResourceManager.GetString("App_Notify_Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App launched.
        ///Can be opened from the task tray. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string App_Notify_WakeUp {
            get {
                return ResourceManager.GetString("App_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play time : {0} hour(s) {1} minute(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameApp_Notify_PlayTime_Result {
            get {
                return ResourceManager.GetString("GameApp_Notify_PlayTime_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Impact launch detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameApp_Notify_WakeUp {
            get {
                return ResourceManager.GetString("GameApp_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Warning] The application is currently in safe mode and is read-only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning_SafeMode {
            get {
                return ResourceManager.GetString("Warning_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enhancement Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_EnhancementCalculator {
            get {
                return ResourceManager.GetString("WindowName_EnhancementCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Announcement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_GameAnnouncement {
            get {
                return ResourceManager.GetString("WindowName_GameAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle Chronicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_GameRecord {
            get {
                return ResourceManager.GetString("WindowName_GameRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real-Time Notes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_RealTimeNote {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spiral Abyss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_SpiralAbyss {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Diary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_TravelersDiary {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Pathbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowName_TravelersDiaryDetail {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetail", resourceCulture);
            }
        }
    }
}
