//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to save the screenshot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Error_FailedSaveScreenshot {
            get {
                return ResourceManager.GetString("App_Error_FailedSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New screenshot was saved! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Notify_Screenshot_Saved {
            get {
                return ResourceManager.GetString("App_Notify_Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App launched.
        ///Can be opened from the task tray. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Notify_WakeUp {
            get {
                return ResourceManager.GetString("App_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert from json. 
        ///--- Received Data ---
        ///{0}
        ///--- Data End --- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_Endpoint_JsonParseInvalid {
            get {
                return ResourceManager.GetString("Error_API_Endpoint_JsonParseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Root is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_Endpoint_RootIsNull {
            get {
                return ResourceManager.GetString("Error_API_Endpoint_RootIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inconsistent UID format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_400 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target player not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_404 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This API is currently unavailable due to destructive changes made by an in-game update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_424 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many requests. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_429 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal server error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_500 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This API is currently unavailable due to the service being temporarily suspended. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_API_EnkaNetwork_503 {
            get {
                return ResourceManager.GetString("Error_API_EnkaNetwork_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not the same account for which you are requesting reauthentication. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BattleAuth_AccountMismatch {
            get {
                return ResourceManager.GetString("Error_BattleAuth_AccountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check again the URL is correct and you are logged in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BattleAuth_ColudNotAuthentication_Message {
            get {
                return ResourceManager.GetString("Error_BattleAuth_ColudNotAuthentication_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not authentication. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BattleAuth_CouldNotAuthentication {
            get {
                return ResourceManager.GetString("Error_BattleAuth_CouldNotAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Authentication. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BattleAuth_FailedToAuthentication {
            get {
                return ResourceManager.GetString("Error_BattleAuth_FailedToAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character ID ({0}) was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CalculateResult_CharacterNotFound {
            get {
                return ResourceManager.GetString("Error_CalculateResult_CharacterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - {1} is unknown data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CalculateResult_InvalidItemID {
            get {
                return ResourceManager.GetString("Error_CalculateResult_InvalidItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only support 3 talents. this character has {0} talent(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CalculateResult_InvalidTalentCount {
            get {
                return ResourceManager.GetString("Error_CalculateResult_InvalidTalentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load talents infomation.
        ///Error Log
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_FailedToLoadTalentInfomation {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_FailedToLoadTalentInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load talents infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_FailedToLoadTalentsInfomation {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_FailedToLoadTalentsInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid account data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_InvalidSaveData {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_InvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talents count is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_InvalidTalentCount {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_InvalidTalentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} data error(s) occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_MultipleError {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_MultipleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for talents infomation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_WaitForTalentInfomation {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_WaitForTalentInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please open it again after a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_WaitForTalentInfomation_Message {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_WaitForTalentInfomation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently working in another thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterCalculator_WorkingOtherThread {
            get {
                return ResourceManager.GetString("Error_CharacterCalculator_WorkingOtherThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This character is missing data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_CharacterDetailIsMissing {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_CharacterDetailIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} has no data on the volunteer database yet.
        ///Please reopen it again after a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_CharacterDetailIsMissing_Message {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_CharacterDetailIsMissing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have the character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_DontHaveCharacter {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_DontHaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load talent infomation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_FailToLoadTalentInfomation {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_FailToLoadTalentInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErrorCode : {0}
        ///Message : {1}
        ///{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_HoYoLabAPIException {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_HoYoLabAPIException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attempt limit has reached. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterDetail_ReachedRetryCount {
            get {
                return ResourceManager.GetString("Error_CharacterDetail_ReachedRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to calculated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CharacterResult_FailedToLoad {
            get {
                return ResourceManager.GetString("Error_CharacterResult_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception error occurred during reading config file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Config_FailToLoad {
            get {
                return ResourceManager.GetString("Error_Config_FailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_GameRecord_FailedToLoad {
            get {
                return ResourceManager.GetString("Error_GameRecord_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The corresponding HoYoLab account (UID: {0}) is not authenticated and therefore cannot be accessed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_HoYoLabAccount_NotAuthenticated {
            get {
                return ResourceManager.GetString("Error_HoYoLabAccount_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In your HoYoLab account, you do not possess the &apos;UID {0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_HoYoLabAccount_UIDNotFound {
            get {
                return ResourceManager.GetString("Error_HoYoLabAccount_UIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load from database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LoadTravelersDiaryDetail_FailedToLoadFromDatabase {
            get {
                return ResourceManager.GetString("Error_LoadTravelersDiaryDetail_FailedToLoadFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not start because multiple startups were detected.
        ///Arguments invoked : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Program_MultipleLaunched {
            get {
                return ResourceManager.GetString("Error_Program_MultipleLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open registry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Registry_FailedToOpen {
            get {
                return ResourceManager.GetString("Error_Registry_FailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use 2+ consecutive path delimiter characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_DoubleSeparator {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_DoubleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use a space as the first character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_FirstCharacterIsSpace {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_FirstCharacterIsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_InvalidCharacters {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use a directory delimiter character at the end of the format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_ScreenshotFormat_LastCharacterIsSeparate {
            get {
                return ResourceManager.GetString("Error_ScreenshotFormat_LastCharacterIsSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Does not match uid ({0} -&gt; {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_SpiralAbyssFile_DoesNotMatchUID {
            get {
                return ResourceManager.GetString("Error_SpiralAbyssFile_DoesNotMatchUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert new standard format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_SpiralAbyssFile_FailedConvert {
            get {
                return ResourceManager.GetString("Error_SpiralAbyssFile_FailedConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid File version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_SpiralAbyssFile_InvalidFileVersion {
            get {
                return ResourceManager.GetString("Error_SpiralAbyssFile_InvalidFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data was saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_SpiralAbyssFile_RegistryNotFound {
            get {
                return ResourceManager.GetString("Error_SpiralAbyssFile_RegistryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown File version. (Ver{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_SpiralAbyssFile_UnknownFileVersion {
            get {
                return ResourceManager.GetString("Error_SpiralAbyssFile_UnknownFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while drawing the graph. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TimeGraph_FailedToDrawGraph {
            get {
                return ResourceManager.GetString("Error_TimeGraph_FailedToDrawGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The event times of the previous and next data are in conflict; it is possible that the API-side data has been updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TravelersDiaryDetail_Conflict {
            get {
                return ResourceManager.GetString("Error_TravelersDiaryDetail_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to output csv. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TravelersDiaryDetailList_FailedToCsvOutput {
            get {
                return ResourceManager.GetString("Error_TravelersDiaryDetailList_FailedToCsvOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TravelersDiaryDetailList_FailedToLoadDatabase {
            get {
                return ResourceManager.GetString("Error_TravelersDiaryDetailList_FailedToLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TravelersDiaryDetailList_InvalidData {
            get {
                return ResourceManager.GetString("Error_TravelersDiaryDetailList_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play time : {0} hour(s) {1} minute(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameApp_Notify_PlayTime_Result {
            get {
                return ResourceManager.GetString("GameApp_Notify_PlayTime_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genshin Impact launch detected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameApp_Notify_WakeUp {
            get {
                return ResourceManager.GetString("GameApp_Notify_WakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (UID:{1}) will remove from the account list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_Message {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove this account? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_Title {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_AccountDisconnect_WindowTitle {
            get {
                return ResourceManager.GetString("Message_AccountDisconnect_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please open the game and earn rewards. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_ExpeditionCompleted_Description {
            get {
                return ResourceManager.GetString("Notify_ExpeditionCompleted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expendition is completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_ExpeditionCompleted_Title {
            get {
                return ResourceManager.GetString("Notify_ExpeditionCompleted_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently {0} of realm coins are stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_RealmCoin_Current {
            get {
                return ResourceManager.GetString("Notify_RealmCoin_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm coins reached max. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_RealmCoinMax_Title {
            get {
                return ResourceManager.GetString("Notify_RealmCoinMax_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realm coins reached value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_RealmCoinReached_Title {
            get {
                return ResourceManager.GetString("Notify_RealmCoinReached_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently {0} of original resins are stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_Resin_Current {
            get {
                return ResourceManager.GetString("Notify_Resin_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original resin reached max. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_ResinMax_Title {
            get {
                return ResourceManager.GetString("Notify_ResinMax_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orignal resin reached value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_ResinReached_Title {
            get {
                return ResourceManager.GetString("Notify_ResinReached_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t forget to use Parametric Transformer this week! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_TransformerReached_Description {
            get {
                return ResourceManager.GetString("Notify_TransformerReached_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parametric Transformer is now available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notify_TransformerReached_Title {
            get {
                return ResourceManager.GetString("Notify_TransformerReached_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Character_Level {
            get {
                return ResourceManager.GetString("UI_Character_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [C{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ConstellationLevel {
            get {
                return ResourceManager.GetString("UI_ConstellationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [C6] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ConstellationLevelMax {
            get {
                return ResourceManager.GetString("UI_ConstellationLevelMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friendship Level : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_FriendshipLevel {
            get {
                return ResourceManager.GetString("UI_FriendshipLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Talent_Level {
            get {
                return ResourceManager.GetString("UI_Talent_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Weapons_Level {
            get {
                return ResourceManager.GetString("UI_Weapons_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refinement Rank {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Weapons_RefinementRank {
            get {
                return ResourceManager.GetString("UI_Weapons_RefinementRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Days: {0} Achieve: {1}
        ///Spiral Abyss: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_AccountInfo_Infomation {
            get {
                return ResourceManager.GetString("UIName_AccountInfo_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load game data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_AccountInfo_Infomation_Failed {
            get {
                return ResourceManager.GetString("UIName_AccountInfo_Infomation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_CharacterFrame_FailedToLoad {
            get {
                return ResourceManager.GetString("UIName_CharacterFrame_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_CharacterFrame_Nothing {
            get {
                return ResourceManager.GetString("UIName_CharacterFrame_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle_Common {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle2_1 {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latter Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Battle2_2 {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Battle2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Floor {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Update : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_LatestUpdate {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_LatestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Level {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Locked {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result of Spiral Abyss: Season {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_ResultTitle {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_SeasonName {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_SeasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIName_SpiralAbyss_Timestamp {
            get {
                return ResourceManager.GetString("UIName_SpiralAbyss_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Warning] The application is currently in safe mode and is read-only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_SafeMode {
            get {
                return ResourceManager.GetString("Warning_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BatchWindow_MultipleCharacterName {
            get {
                return ResourceManager.GetString("WindowName_BatchWindow_MultipleCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple characters training setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BatchWindow_MultiText {
            get {
                return ResourceManager.GetString("WindowName_BatchWindow_MultiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}&apos;s goal training setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BatchWindow_SingleText {
            get {
                return ResourceManager.GetString("WindowName_BatchWindow_SingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talent : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BatchWindow_TalentName {
            get {
                return ResourceManager.GetString("WindowName_BatchWindow_TalentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BattleAuth_AuthAndBack {
            get {
                return ResourceManager.GetString("WindowName_BattleAuth_AuthAndBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click &quot;Auth&quot; then after logged in HoYoLab. If approved, this window will automatically close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_BattleAuth_Message {
            get {
                return ResourceManager.GetString("WindowName_BattleAuth_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculate Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CalculateResult {
            get {
                return ResourceManager.GetString("WindowName_CalculateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... {0} / {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CalculateResult_Loading {
            get {
                return ResourceManager.GetString("WindowName_CalculateResult_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enhancement Progression Calculator+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_Button_AllEdit {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_Button_AllEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_Button_Edit {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Needs update talents infomation. Do you want to allow this action? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_Confirm_UpdateTalentsInfomation {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_Confirm_UpdateTalentsInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New characters found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_NewCharacterFound {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_NewCharacterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reacquire all talents information in bulk?
        ///This may take some time depending on number of characters.
        ///
        ///*This window will automatically close when updating. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_UpdateTalentsInfomation_Description {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_UpdateTalentsInfomation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update talents infomation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterCalculator_UpdateTalentsInfomation_Title {
            get {
                return ResourceManager.GetString("WindowName_CharacterCalculator_UpdateTalentsInfomation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterDetail {
            get {
                return ResourceManager.GetString("WindowName_CharacterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unequipped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterDetail_NoArtifact {
            get {
                return ResourceManager.GetString("WindowName_CharacterDetail_NoArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide ▲ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterDetail_Talent_Hide {
            get {
                return ResourceManager.GetString("WindowName_CharacterDetail_Talent_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show more ▼ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_CharacterDetail_Talent_ShowMore {
            get {
                return ResourceManager.GetString("WindowName_CharacterDetail_Talent_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enhancement Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_EnhancementCalculator {
            get {
                return ResourceManager.GetString("WindowName_EnhancementCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Announcement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameAnnouncement {
            get {
                return ResourceManager.GetString("WindowName_GameAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battle Chronicle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameRecord {
            get {
                return ResourceManager.GetString("WindowName_GameRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} AR.{1} | Achievement : {2} | Spiral Abyss : {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameRecord_HeaderText {
            get {
                return ResourceManager.GetString("WindowName_GameRecord_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexplored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameRecord_HeaderText_NoSpiralAbyss {
            get {
                return ResourceManager.GetString("WindowName_GameRecord_HeaderText_NoSpiralAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WR. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_GameRecord_WorldRankText {
            get {
                return ResourceManager.GetString("WindowName_GameRecord_WorldRankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieving {1} history for {0}...
        ///Pages currently retrieved : {2} pages
        ///Total pages : {3} pages
        ///Progress : {4}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_LoadTravelersDiaryDetail_LoadingProgress {
            get {
                return ResourceManager.GetString("WindowName_LoadTravelersDiaryDetail_LoadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real-Time Notes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_APIError {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_APIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_Daily_Completed {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_Daily_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra Available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_Daily_NotExtraClaimed {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_Daily_NotExtraClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} left of {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_DiscountWeeklyBossText {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_DiscountWeeklyBossText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_ExceptionError {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Code : {0}
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_ExceptionErrorDetail {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_ExceptionErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_ExpeditionCompleted {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_ExpeditionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_Locked {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_MaxOut {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_MaxOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TimeLeft {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformAvailable {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}D に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformOngoingDay {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformOngoingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformOngoingHour {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformOngoingHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}M に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformOngoingMinute {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformOngoingMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformOngoingSecond {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformOngoingSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_RealTimeNote_TransformOngoingText {
            get {
                return ResourceManager.GetString("WindowName_RealTimeNote_TransformOngoingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spiral Abyss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elm. Bursts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_ElementalBurstsUnleashed {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_ElementalBurstsUnleashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elm. Skills に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_ElementalSkillsCast {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_ElementalSkillsCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_Locked {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damage Taken に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_MostDamageTaken {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_MostDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Most Defeats に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_MostDefeats {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_MostDefeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Most Played に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_MostPlayedCharacters {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_MostPlayedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Damages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_SpiralAbyss_StrongestSingleStrike {
            get {
                return ResourceManager.GetString("WindowName_SpiralAbyss_StrongestSingleStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day&apos;s data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimeGraph_DayName {
            get {
                return ResourceManager.GetString("WindowName_TimeGraph_DayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data for {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimeGraph_MonthName {
            get {
                return ResourceManager.GetString("WindowName_TimeGraph_MonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimeGraph_VersionName {
            get {
                return ResourceManager.GetString("WindowName_TimeGraph_VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimeGraph_WeekName {
            get {
                return ResourceManager.GetString("WindowName_TimeGraph_WeekName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimerDisplay_State_Active {
            get {
                return ResourceManager.GetString("WindowName_TimerDisplay_State_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimerDisplay_State_Background {
            get {
                return ResourceManager.GetString("WindowName_TimerDisplay_State_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TimerDisplay_State_NotRunning {
            get {
                return ResourceManager.GetString("WindowName_TimerDisplay_State_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Diary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiary {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Traveler&apos;s Pathbook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetail {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading page {2} of {0} {1} data now... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Downloading {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   this month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Downloading_ThisMonth {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Downloading_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Name_EventTime {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Name_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Name_EventTypeID {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Name_EventTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Name_EventTypeName {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Name_EventTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obtained に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_Name_ObtainedCount {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_Name_ObtainedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma Separated Values (*.csv)|*.csv|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_SaveToCsv_Filter {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_SaveToCsv_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose select output directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowName_TravelersDiaryDetailList_SaveToCsv_Title {
            get {
                return ResourceManager.GetString("WindowName_TravelersDiaryDetailList_SaveToCsv_Title", resourceCulture);
            }
        }
    }
}
