//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageUserData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageUserData() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.Languages.ManageUserData", typeof(ManageUserData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancelled_DeleteData_Message {
            get {
                return ResourceManager.GetString("Cancelled_DeleteData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete processing has been interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancelled_DeleteData_Title {
            get {
                return ResourceManager.GetString("Cancelled_DeleteData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We look forward to seeing you again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete_DeletedData_Message {
            get {
                return ResourceManager.GetString("Complete_DeletedData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User data has been successfully deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete_DeletedData_Title {
            get {
                return ResourceManager.GetString("Complete_DeletedData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data recovery process has been completed, but login information has not been transferred.
        ///Please log in again to access the convenient functions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete_Overwrite_Message {
            get {
                return ResourceManager.GetString("Complete_Overwrite_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application data was successfully overwritten. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete_Overwrite_Title {
            get {
                return ResourceManager.GetString("Complete_Overwrite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once this process is executed, it cannot be undone unless there is a backup.
        ///Are you sure you want to do this?
        ///The application will restart after this operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_Confirm_Message {
            get {
                return ResourceManager.GetString("Delete_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_Confirm_Title {
            get {
                return ResourceManager.GetString("Delete_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data to be lost are as follows...
        ///* Playing time data
        ///* Login infomation
        ///* Setting files
        ///* Archived Traveler&apos;s pathbook data for saved all accounts
        ///* Archived spiral abyss data for saved all accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_Notice_Message {
            get {
                return ResourceManager.GetString("Delete_Notice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation will delete all personal data in the application! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete_Notice_Title {
            get {
                return ResourceManager.GetString("Delete_Notice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while deleting data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_DeletedData_Title {
            get {
                return ResourceManager.GetString("Error_DeletedData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while overwriting application data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Overwrite_Title {
            get {
                return ResourceManager.GetString("Error_Overwrite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to recovery. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedToRecovery {
            get {
                return ResourceManager.GetString("FailedToRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All personal data stored in this app will be deleted.
        ///After the operation, it cannot be undone.
        ///
        ///Are you really sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FinalConfirm_Message {
            get {
                return ResourceManager.GetString("FinalConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THIS IS THE FINAL CONFIRMATION. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FinalConfirm_Title {
            get {
                return ResourceManager.GetString("FinalConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation will overwrite all data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBackup_FinalConfirm_Message {
            get {
                return ResourceManager.GetString("LoadBackup_FinalConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to perform this operation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBackup_FinalConfirm_Title {
            get {
                return ResourceManager.GetString("LoadBackup_FinalConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the file from which you want to load. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBackup_LoadTo_Title {
            get {
                return ResourceManager.GetString("LoadBackup_LoadTo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We basically do not recommend using this function except to recover or move data.
        ///If you must perform this operation, we strongly recommend that you obtain a backup before doing so.
        ///Do you still wish to proceed with this operation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBackup_Notice_Message {
            get {
                return ResourceManager.GetString("LoadBackup_Notice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation may cause all data in the application to be lost! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadBackup_Notice_Title {
            get {
                return ResourceManager.GetString("LoadBackup_Notice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveBackup_Failed_Title {
            get {
                return ResourceManager.GetString("SaveBackup_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the backup file to save to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveBackup_SaveTo_Title {
            get {
                return ResourceManager.GetString("SaveBackup_SaveTo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All data except login data has been backed up. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveBackup_Success_Message {
            get {
                return ResourceManager.GetString("SaveBackup_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup successfully created! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveBackup_Success_Title {
            get {
                return ResourceManager.GetString("SaveBackup_Success_Title", resourceCulture);
            }
        }
    }
}
