//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Checker.resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenshinAsset {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenshinAsset() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Checker.resource.GenshinAsset", typeof(GenshinAsset).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ver.1.0
        ///Ver.1.1
        ///Ver.1.2
        ///Ver.1.3
        ///Ver.1.4
        ///Ver.1.5
        ///Ver.1.6
        ///Ver.2.0
        ///Ver.2.1
        ///Ver.2.2
        ///Ver.2.3
        ///Ver.2.4
        ///Ver.2.5
        ///Ver.2.6
        ///Ver.2.7
        ///Ver.2.8
        ///Ver.3.0
        ///Ver.3.1
        ///Ver.3.2
        ///Ver.3.3
        ///Ver.3.4
        ///Ver.3.5
        ///Ver.3.6
        ///Ver.3.7
        ///Ver.3.8
        ///Ver.4.0
        ///Ver.4.1
        ///Ver.4.2
        ///Ver.4.3
        ///Ver.4.4
        ///Ver.4.5
        ///Ver.4.6
        ///Ver.4.7
        ///Ver.4.8
        ///Ver.5.0
        ///Ver.5.1
        ///Ver.5.2
        ///Ver.5.3
        ///Ver.5.4
        ///Ver.5.5
        ///Ver.5.6
        ///Ver.5.7
        ///Ver.5.8
        ///Ver.6.0
        ///Ver.6.1
        ///Ver.6.2
        ///Ver.6.3
        ///Ver.6.4
        ///Ver.6.5
        ///Ver.6.6
        ///Ver.6.7
        ///Ver.6.8
        ///Ver.7.0
        ///Ver.7.1
        ///Ver.7.2
        ///Ver.7.3
        ///Ver.7.4        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeasonName {
            get {
                return ResourceManager.GetString("SeasonName", resourceCulture);
            }
        }
    }
}
